[2025-04-11T07:06:28.544+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: proyecto_bigdata.guardar_postgresql manual__2025-04-11T07:06:22.683039+00:00 [queued]>
[2025-04-11T07:06:28.552+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: proyecto_bigdata.guardar_postgresql manual__2025-04-11T07:06:22.683039+00:00 [queued]>
[2025-04-11T07:06:28.553+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-11T07:06:28.565+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): guardar_postgresql> on 2025-04-11 07:06:22.683039+00:00
[2025-04-11T07:06:28.570+0000] {standard_task_runner.py:60} INFO - Started process 449 to run task
[2025-04-11T07:06:28.572+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'proyecto_bigdata', 'guardar_postgresql', 'manual__2025-04-11T07:06:22.683039+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/proyecto_bigdata_dag.py', '--cfg-path', '/tmp/tmpmcs9ij70']
[2025-04-11T07:06:28.574+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask guardar_postgresql
[2025-04-11T07:06:28.620+0000] {task_command.py:423} INFO - Running <TaskInstance: proyecto_bigdata.guardar_postgresql manual__2025-04-11T07:06:22.683039+00:00 [running]> on host 4193653a407b
[2025-04-11T07:06:28.689+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='proyecto_bigdata' AIRFLOW_CTX_TASK_ID='guardar_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T07:06:22.683039+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-11T07:06:22.683039+00:00'
[2025-04-11T07:06:28.732+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-11T07:06:28.741+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=proyecto_bigdata, task_id=guardar_postgresql, execution_date=20250411T070622, start_date=20250411T070628, end_date=20250411T070628
[2025-04-11T07:06:28.787+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-11T07:06:28.809+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
